### ISSUE TITLE
`cephadm_custom_repos: true` prevents installation of Reef on Ubuntu 22.04

### ISSUE THREAD

**Issue by PC-Admin** [stackhpc/ansible-collection-cephadm#150]
Turns out setting 'cephadm_custom_repos' as true installs quincy... the default version on Ubuntu 22.04! But this causes the playbook to ignore `cephadm_ceph_release`:
```
cephadm_ceph_release: "reef"
cephadm_custom_repos: true  # Should be enabled for Ubuntu 22.04
```

Results in:
```
root@storage-13-09002:/# ceph version
ceph version 17.2.7 (b12291d110049b2f35e32e0de30d70e9a4c060d2) quincy (stable)
```

On this page we're told "If using Ubuntu 22.04 this should be set to true." for cephadm_custom_repos: https://github.com/stackhpc/ansible-collection-cephadm/blob/083dcea047f477d7a44da40c34d7c216b1026a44/roles/cephadm/README.md

But why is that? Is there any problem with using the custom repos for Ubuntu 22.04?

**Comment by cityofships** [comment]
I believe `cephadm_custom_repos` variable existed before Reef was released. The problem at that time was that Quincy packages were not available for Jammy, as a workaround Focal packages could have been used and it worked just fine. There is the same situation right now with Noble vs. Jammy.

> Turns out setting 'cephadm_custom_repos' as true installs quincy... the default version on Ubuntu 22.04! But this causes the playbook to ignore `cephadm_ceph_release`:

The variable does precisely that, if set - overrides the official repositories to arbitrary ones, so it's possible to mix & match distros & Ceph releases and ignore the contents of `cephadm_ceph_release`. I'll try to correct the docs to emphasise that.

Note that the above applies just for the `cephadm` package installation, it's still possible to have e.g. Quincy's cephadm installed but the actual version of Ceph in the containers set to Reef. This is not recommended though.
