### ISSUE TITLE
Cephadm and Podman version

### ISSUE THREAD

**Issue by mnasiadka** [stackhpc/ansible-collection-cephadm#6]
Adjust the role to install supported Podman version: https://docs.ceph.com/en/latest/cephadm/compatibility/#compatibility-with-podman-versions

**Comment by cityofships** [comment]
We should consider Ceph releases to be supported by the collection, latest two?

**Comment by mnasiadka** [comment]
Actually this one might get complicated - CentOS AppStream repo has 2.2, which is not supported on any release...

**Comment by jcmdln** [comment]
Personally I'd prefer that this role didn't install docker or podman. My take is that the consumer best knows their environment and can handle installing their preferred runtime prior to using the cephadm role. Maybe podman could be an additional role to handle setup and configuration while allowing users such as myself that kinda need docker to simply not use it in our own playbooks.

**Comment by markgoddard** [comment]
> Personally I'd prefer that this role didn't install docker or podman. My take is that the consumer best knows their environment and can handle installing their preferred runtime prior to using the cephadm role. Maybe podman could be an additional role to handle setup and configuration while allowing users such as myself that kinda need docker to simply not use it in our own playbooks.

Agree that the main cephadm role should not be installing docker or podman. Ideally we'd use a separate (existing?) role or collection. If the collection really must own it, it should be a separate role.
